version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: gaming-platform-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - gaming-network

networks:
  gaming-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  redis-data:
    driver: local 